# Generated by Django 3.2.25 on 2025-04-17 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_gesture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticationsession',
            old_name='last_activity',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='authenticationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biometricprofile',
            name='face_encoding_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='biometricprofile',
            name='gesture_encoding_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='biometricprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='authenticationsession',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_image', models.BinaryField(null=True)),
                ('pattern', models.TextField(help_text='JSON string of grid pattern', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
