# Generated by Django 3.2.25 on 2025-04-19 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_gesture', '0002_auto_20250418_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationsession',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='authenticationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='authenticationsession',
            unique_together={('user', 'session_key')},
        ),
    ]
