# Generated by Django 5.1.4 on 2025-02-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='auth_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gesture_pattern',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pattern_image',
            field=models.ImageField(blank=True, null=True, upload_to='pattern_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pattern_position_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pattern_position_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pattern',
            field=models.TextField(blank=True, null=True),
        ),
    ]
