# Generated by Django 5.1.4 on 2025-02-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_userprofile_auth_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pattern_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
